<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import api from '../../../services/api';
import { useToastStore } from '../../../stores/toast';

const route = useRoute();
const router = useRouter();
const toastStore = useToastStore();

const tokenInput = ref((route.query.token as string) || '');
const uidInput = ref((route.query.uid as string) || '');
const isVerifying = ref(false);

const executeVerification = async () => {
  if (!tokenInput.value || !uidInput.value) {
    toastStore.show('Please provide both the UID and verification token.', 'warning');
    return;
  }

  isVerifying.value = true;
  try {
    const res = await api.post('/auth/verify-email', {
      token: tokenInput.value,
      uid: uidInput.value
    });

    if (res.data?.success) {
      toastStore.show('Email verified successfully! You can now log in.', 'success');
      router.push('/login');
    }
  } catch (err: any) {
    toastStore.show(err.response?.data?.message || 'Email verification failed.', 'error');
  } finally {
    isVerifying.value = false;
  }
};

onMounted(() => {
  if (tokenInput.value && uidInput.value) {
    executeVerification();
  }
});
</script>

<template>
  <div class="min-h-screen flex items-center justify-center bg-github-bg px-4 font-sans text-github-text">
    <div class="w-full max-w-sm bg-github-surface border border-github-border p-6 rounded-[6px] flex flex-col gap-5">
      
      <div class="text-center">
        <h1 class="text-xl font-bold text-github-text mb-1">
          Verify Email Address
        </h1>
        <p class="text-xs text-github-secondary">
          Enter the verification details generated by the system.
        </p>
      </div>

      <div class="flex flex-col gap-4">
        <div>
          <label class="block text-xs font-semibold text-github-text mb-1.5">
            Student User ID (UID)
          </label>
          <input
            v-model="uidInput"
            type="text"
            placeholder="User UID generated at signup"
            class="github-input w-full"
          />
        </div>

        <div>
          <label class="block text-xs font-semibold text-github-text mb-1.5">
            Verification Token
          </label>
          <input
            v-model="tokenInput"
            type="text"
            placeholder="Token key shown in server terminal logs"
            class="github-input w-full"
          />
        </div>

        <button
          @click="executeVerification"
          :disabled="isVerifying"
          class="github-button-primary w-full mt-2 flex justify-center items-center h-9"
        >
          <span v-if="isVerifying" class="border-2 border-white/20 border-t-white h-3.5 w-3.5 rounded-full animate-spin"></span>
          <span v-else>Verify Account</span>
        </button>
      </div>

      <div class="text-center text-xs text-github-secondary">
        <router-link to="/login" class="text-github-accent hover:underline font-semibold">
          Back to Sign In
        </router-link>
      </div>

    </div>
  </div>
</template>
