<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import api from '../../../services/api';
import { useToastStore } from '../../../stores/toast';

const route = useRoute();
const router = useRouter();
const toastStore = useToastStore();

const tokenInput = ref((route.query.token as string) || '');
const uidInput = ref((route.query.uid as string) || '');
const isVerifying = ref(false);

const executeVerification = async () => {
  if (!tokenInput.value || !uidInput.value) {
    toastStore.show('Please provide both the UID and verification token.', 'warning');
    return;
  }

  isVerifying.value = true;
  try {
    const res = await api.post('/auth/verify-email', {
      token: tokenInput.value,
      uid: uidInput.value
    });

    if (res.data?.success) {
      toastStore.show('Email verified successfully! You can now log in.', 'success');
      router.push('/login');
    }
  } catch (err: any) {
    toastStore.show(err.response?.data?.message || 'Email verification failed.', 'error');
  } finally {
    isVerifying.value = false;
  }
};

onMounted(() => {
  if (tokenInput.value && uidInput.value) {
    executeVerification();
  }
});
</script>

<template>
  <div class="min-h-screen flex items-center justify-center bg-slate-100 dark:bg-slate-950 px-4 transition-colors duration-300">
    <div class="w-full max-w-md bg-white/70 dark:bg-slate-900/60 backdrop-blur-md border border-slate-200 dark:border-slate-800 p-8 rounded-3xl shadow-2xl flex flex-col gap-6">
      
      <div class="text-center">
        <h1 class="text-2xl font-extrabold text-slate-800 dark:text-slate-100 mb-1">
          Verify Email Address
        </h1>
        <p class="text-xs text-slate-500">
          Enter the verification details generated by the system.
        </p>
      </div>

      <div class="flex flex-col gap-4">
        <div>
          <label class="block text-[10px] font-bold uppercase tracking-wider text-slate-500 mb-1">
            Student User ID (UID)
          </label>
          <input
            v-model="uidInput"
            type="text"
            placeholder="User UID generated at signup"
            class="w-full px-4 py-2 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/50 focus:outline-none dark:text-slate-100"
          />
        </div>

        <div>
          <label class="block text-[10px] font-bold uppercase tracking-wider text-slate-500 mb-1">
            Verification Token
          </label>
          <input
            v-model="tokenInput"
            type="text"
            placeholder="Token key shown in server terminal logs"
            class="w-full px-4 py-2 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/50 focus:outline-none dark:text-slate-100"
          />
        </div>

        <button
          @click="executeVerification"
          :disabled="isVerifying"
          class="w-full mt-2 py-3 rounded-xl bg-primary-500 hover:bg-primary-600 text-white font-semibold text-sm transition-colors cursor-pointer flex justify-center items-center"
        >
          <span v-if="isVerifying" class="border-2 border-white/30 border-t-white h-4 w-4 rounded-full animate-spin"></span>
          <span v-else>Verify Account</span>
        </button>
      </div>

      <div class="text-center text-xs">
        <router-link to="/login" class="text-primary-500 font-bold">
          Back to Sign In
        </router-link>
      </div>

    </div>
  </div>
</template>
